name: Publish CORE

on:
  push:
    branches:
      - 'deploy/core'

jobs:
  publish_npm:
    name: Publish NPM - CORE
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn install
    - run: yarn test
    - run: yarn build
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish_github:
    name: Publish GitHub Package - CORE
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@themarkwill'
    - run: npm install
    - run: npm test
    - run: npm run build
    - name: Update package.json to GitHubName
      uses: jossef/action-set-json-field@v1
      with:
        file: package.json
        field: name
        value: '@themarkwill/the-math'
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}